package mcwarfare.common.asm;

import java.util.Arrays;

import com.google.common.eventbus.EventBus;

import cpw.mods.fml.common.DummyModContainer;
import cpw.mods.fml.common.LoadController;
import cpw.mods.fml.common.ModMetadata;

public class WFModContainer extends DummyModContainer {
	
	public WFModContainer() {
		super(new ModMetadata());
		ModMetadata meta = getMetadata();
		meta.name = "Minecraft Warfare Core";
		meta.version = "0.1";
		meta.modId = "mcWarfareCore";
		meta.authorList = Arrays.asList("cr3wp", "diesieben07");
		meta.description = "No Description yet";
		meta.autogenerated = false;
	}

	@Override
	public boolean registerBus(EventBus bus, LoadController controller) {
		return true;
	}
}